### ISSUE TITLE
Need to use LiquidCrystal_I2C

### ISSUE THREAD

**Issue by kabidey** [grahamwhaley/DSPham#26]
Hi Graham, i am not good with modifying the codes, need the thing modified to display in 1602 I2C, i cannot do it. Please help.

**Comment by grahamwhaley** [comment]
Hi @kabidey,
 if you can tell me which I2C screen you have then I might be able to help. As the screen I used (Grove) is already I2C, it might be not too difficult to make the changes.

Ideally your screen will be supported by the menu library I use:
https://github.com/neu-rah/ArduinoMenu

Merry Xmas!
 Graham (replying via email - hope it renders OK. I will have more time to look after xmas).

**Comment by kabidey** [comment]
My display is the parallel 1602 lcd display with a I2C adapter soldered.

**Comment by grahamwhaley** [comment]
Thanks @kabidey,

 I think you will probably want to use the ' • HD44780 I2C’ support from the F Malpartida's LCDs :
https://bitbucket.org/fmalpartida/new-liquidcrystal/wiki/Home

A very good first step will be to see if you can get the arduino menu examples working , for instance, for your screen probably try:

https://github.com/neu-rah/ArduinoMenu/tree/master/examples/LCD_Malpartida/I2C/I2C

If you get that working, you are probably 75% of the way to getting DSPham working on your display. The other thing you will need to modify in DSPham is the ‘lcd.cpp’  to change from using the ‘rgb_lcd’ driver to using the malpartida I2C or similar driver. https://github.com/grahamwhaley/DSPham/blob/master/lcd.cpp

Graham

**Comment by kabidey** [comment]
I tried, but could not do it. So I ordered a grove LCD ;)

**Comment by grahamwhaley** [comment]
OK @kabidey, thanks for letting me know. Shall we close this Issue now, and you can open a new one if you get stuck with the new display?

**Comment by kabidey** [comment]
Sure, thanks
