### ISSUE TITLE
Compiling DSPham.ini

### ISSUE THREAD

**Issue by codehopper199** [grahamwhaley/DSPham#5]
Hello Graham,
Very interested in your Radcom article as I have been trying to improve the audio on my IC7300 to get rid of some of noise on the output. I am not a programmer so could do with a bit of help if that is possible.
I am trying to compile DSPham.ino but it fails every time. I believe I have all the necessary files within my arduino IDE but it always comes back with an error as below where it cannot find global.h
Any help would be much appreciated.
Rod G0IYQ

Arduino: 1.8.13 (Windows 10), TD: 1.53, Board: "Teensy 4.0, Serial, 600 MHz, Faster, US English"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\rodmi\Documents\Arduino\libraries -fqbn=teensy:avr:teensy40:usb=serial,speed=600,opt=o2std,keys=en-us -ide-version=10813 -build-path C:\Users\rodmi\AppData\Local\Temp\arduino_build_958171 -warnings=none -build-cache C:\Users\rodmi\AppData\Local\Temp\arduino_cache_775077 -verbose C:\Users\rodmi\AppData\Local\Temp\untitled2054921278.tmp\sketch_feb18a\sketch_feb18a.ino

C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\rodmi\Documents\Arduino\libraries -fqbn=teensy:avr:teensy40:usb=serial,speed=600,opt=o2std,keys=en-us -ide-version=10813 -build-path C:\Users\rodmi\AppData\Local\Temp\arduino_build_958171 -warnings=none -build-cache C:\Users\rodmi\AppData\Local\Temp\arduino_cache_775077 -verbose C:\Users\rodmi\AppData\Local\Temp\untitled2054921278.tmp\sketch_feb18a\sketch_feb18a.ino

Using board 'teensy40' from platform in folder: C:\Program Files (x86)\Arduino\hardware\teensy\avr

Using core 'teensy4' from platform in folder: C:\Program Files (x86)\Arduino\hardware\teensy\avr

Detecting libraries used...

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "C:\\Users\\rodmi\\AppData\\Local\\Temp\\arduino_build_958171\\sketch\\sketch_feb18a.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for Audio.h: [Audio@1.3]

ResolveLibrary(Audio.h)

  -> candidates: [Audio@1.3]

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\Audio" "C:\\Users\\rodmi\\AppData\\Local\\Temp\\arduino_build_958171\\sketch\\sketch_feb18a.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for SPI.h: [SPI@1.0]

ResolveLibrary(SPI.h)

  -> candidates: [SPI@1.0]

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\Audio" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SPI" "C:\\Users\\rodmi\\AppData\\Local\\Temp\\arduino_build_958171\\sketch\\sketch_feb18a.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for SD.h: [SD@1.2.4 SD@1.2.2]

ResolveLibrary(SD.h)

  -> candidates: [SD@1.2.4 SD@1.2.2]

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\Audio" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SPI" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SD" "C:\\Users\\rodmi\\AppData\\Local\\Temp\\arduino_build_958171\\sketch\\sketch_feb18a.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for SerialFlash.h: [SerialFlash@0.5]

ResolveLibrary(SerialFlash.h)

  -> candidates: [SerialFlash@0.5]

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\Audio" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SPI" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SD" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SerialFlash" "C:\\Users\\rodmi\\AppData\\Local\\Temp\\arduino_build_958171\\sketch\\sketch_feb18a.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for Wire.h: [Wire@1.0]

ResolveLibrary(Wire.h)

  -> candidates: [Wire@1.0]

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\Audio" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SPI" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SD" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SerialFlash" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\Wire" "C:\\Users\\rodmi\\AppData\\Local\\Temp\\arduino_build_958171\\sketch\\sketch_feb18a.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for Encoder.h: [Encoder@1.4.1]

ResolveLibrary(Encoder.h)

  -> candidates: [Encoder@1.4.1]

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\Audio" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SPI" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SD" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\SerialFlash" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\Wire" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\libraries\\Encoder" "C:\\Users\\rodmi\\AppData\\Local\\Temp\\arduino_build_958171\\sketch\\sketch_feb18a.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for global.h: []

ResolveLibrary(global.h)C:\Users\rodmi\AppData\Local\Temp\untitled2054921278.tmp\sketch_feb18a\DSPham.ino:7:20: fatal error: global.h: No such file or directory

  -> candidates: []

compilation terminated.

Multiple libraries were found for "SD.h"

 Used: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\SD

 Not used: C:\Program Files (x86)\Arduino\libraries\SD

Using library Audio at version 1.3 in folder: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\Audio 

Using library SPI at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\SPI 

Using library SD at version 1.2.2 in folder: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\SD 

Using library SerialFlash at version 0.5 in folder: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\SerialFlash 

Using library Wire at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\Wire 

Using library Encoder at version 1.4.1 in folder: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\Encoder 

Error compiling for board Teensy 4.0.

**Comment by grahamwhaley** [comment]
Hi Rod,
 thanks for opening the Issue. Nothing obvious leaps out at me, but I'll note a few things and we can try and work our way through it.

First, it looks like you are building on Windows. That should be fine, but I'll note that I build on Linux, and don't have a Windows machine to test on. I'm hoping that is not the problem.

The two primary things I'd expect to be candidates for the problem would be:
 - paths
 - capitalisation

Can I ask, how did you copy the files from github, and what path have you placed them in on your computer? You pretty much need all the files in the top level directory. By far the best way to get the files is by `git` cloning the repository - there are github instructions [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository).  Alternatively, you can I believe grab a zip or tar.gz file of one of the tags from https://github.com/grahamwhaley/DSPham/tags, and unzip that locally on your machine.

Make sure your code is in a directory with the same name as the `.ino` file - so `DSPham` in this case. If not then I suspect the Arduino IDE would not even have opened the `.ino` though, so that probably is not your problem.

Let me know how you grabbed the code and where it is placed (maybe a `pwd` and an `dir` to show the contents), and we'll go from there.

**Comment by grahamwhaley** [comment]
Small update - I just grabbed the `.tar.gz` from the v1.0 tag. I found that it unzipped into a folder called `DSPham-1.0` (gee, thanks github ;-) ). That has to be renamed to plain `DSPham` in order to then work in the IDE.

**Comment by grahamwhaley** [comment]
Hi @codehopper199 - re: our recent email thread, I think you are now building OK, yes?

To summarise, the key items we found were:
 - github zip/tar files place the project in a `DSPham-xxx` folder, but to build in the Arduino IDE the files *must* be in a folder called just `DSPham`
 - The Teensy board config in the Arduino IDE must be set to include the 'Audio' component - I use `Serial+MIDI+Audio`, so I'd generally recommend that.

Correct?

I've got a documentation change ready to merge detailing the first point. Let me know if you are OK with building now, and I'll update the docs and (you or I) can close this issue. Thanks!

**Comment by codehopper199** [comment]
Yes Graham, all correct, will you close the issues please.

Regards,
Rod G0IYQ


Sent from my iPad

On 20 Feb 2021, at 16:12, Graham Whaley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @codehopper199<https://github.com/codehopper199> - re: our recent email thread, I think you are now building OK, yes?

To summarise, the key items we found were:

  *   github zip/tar files place the project in a DSPham-xxx folder, but to build in the Arduino IDE the files must be in a folder called just DSPham
  *   The Teensy board config in the Arduino IDE must be set to include the 'Audio' component - I use Serial+MIDI+Audio, so I'd generally recommend that.

Correct?

I've got a documentation change ready to merge detailing the first point. Let me know if you are OK with building now, and I'll update the docs and (you or I) can close this issue. Thanks!
